export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const INCREAES_PRODUCT = "INCREAES_PRODUCT";
export const DECREASE_PRODUCT = "DECREASE_PRODUCT";
export const GET_PURCHASE_LIST = "GET_PURCHASE_LIST";
